### ISSUE TITLE
タイムラインを更新

### ISSUE THREAD

**Issue by yrinda** [Tama-rb/tamarubykaigi01#29]
https://docs.google.com/spreadsheets/d/16sdFFFvON2TXrFBZe5MmcCJPTMX3tZyR6FR3vi8Sv3M/edit#gid=1398401288

No | 枠 | 担当 | Githubアカウント | タイトル
-- | -- | -- | -- | --
1 | 開催案内 | fuqda |   | -
2 | 基調 | いとうさん |   | なぜテストを書くの？（または書かないの？）
3 | CFP 1 | konchan | @konchan_____(Twitter) | プロになるためのレビューのススメ
4 | Tama 1 | fuqda |   | 激つよエンジニアじゃない私なりのOSSへの取り組み方
5 | CFP 2 | Shu OGAWARA | expajp | brainf*ck処理系で理解するパターンマッチングをつかった疎結合な実装
6 | Tama 2 | けんさん |   | こわくないDSL
7 | CFP 3 | ほたて | hotatekaoru | ぼくらのリファクタリングは裏切らない💪
8 | Tama 3 | しおい |   | たのしいOSSコードリーディング: Let's read "cookies"🍪
9 | CFP 4 | s_naga03 | nagata03 | コードを「見る！書く！見てもらう！」で爆速ステップアップ！(仮)
10 | Tama 4 | makicamelさん |   | Dartに浮気したらRubyは最高だと再認識した話
11 | CFP 5 | alitaso345 | alitaso345 | WebAPIクライアント実装のベストプラクティスを実践する
12 | スポンサー 1 | GMOペパボ |   |  
13 | スポンサー 2 | メドピア |   |  
14 | スポンサー 3 | SanSan |   |  
15 | Tama 5 | tsukaさん |   | RubyistのためのElixir
16 | CFP 6 | Katsumata Ryo | katsumata-ryo | 成長を期待しない目的志向実践のススメ
17 | Tama 6 | おおくらさん |   | 車輪の再発明入門
18 | 特別企画 | hayashiさん( / 志村) |   |  
19 | 基調 | igaigaさん |   | 白魔術師への道
20 | 閉会案内 | fuqda |   | -

**Comment by Shigeyuki-fukuda** [comment]
こちらもDONEなのでクローズ！
